### ISSUE TITLE
Error with signature dump command

### ISSUE THREAD

**Issue by Seidhberendir** [kudelskisecurity/ecdsa-dump-bitcoin#1]
Installed and tried to run the sigdump command, but received the following error:

python rusty-blockparser ./release ~/dojo
SyntaxError: Non-UTF-8 code starting with '\xdb' in file /media/dojo/SATASSD/ecdsa-polynomial-nonce-recurrence-attack/ecdsa-dump-bitcoin/target/release/rusty-blockparser on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

Reviewed the website suggested, but I am at a loss on resolving the issue.  Please advise.

**Comment by amietn** [comment]
Hello @Seidhberendir . Thank you for using our code.

This isn't meant to be run with Python.
The tool can be run via cargo or the executable can be directly executed.

For example:

```
cargo run --release -- sigdump  /path/to/dump-folder ~/.bitcoin
```

or if you built the executable already:

```
./target/release/rusty-blockparser sigdump  /path/to/dump-folder ~/.bitcoin
```
